---


    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
    - name: Copy website files to the server's document root
      copy:
        src: /var/www/html
        dest: FelCloud
        mode: preserve   
    - name: Apply Nginx template
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx     
        
    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx        
    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp
     
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

